from stable_baselines3.safe_ppo.safe_ppo import CombinedLoss

best_hyper = {
    "CartSafe-v0": {
        "n_epochs": 5,
        "normalize_safety_advantage": False,
        "vf_safety_coef": 0.5,
        "normalize_advantage": True,
        "clip_range": 0.2,
        "learning_rate": 0.0001,
        "ent_coef": 0.01,
        "num_envs": 4,
        "n_steps": 2048*4,
        "env_id": "CartSafe-v0",
        "loss_type": CombinedLoss(safety_advantage_factor=0., ratio_estimator="PPO"),
        "gamma": 0.99,
        "gamma_s": 0.995,
        "lagrange_beta": 3,
        "safety_k": 5,
        "reward_bias": 0.0,
        "batch_size": 64,
        "augmented_state_cumulative_cost_zero": False,
        "policy_kwargs": {},
        "max_grad_norm": 0.8,
    },
    "SafetyBallRun-v0": {
        "n_epochs": 5,
        "normalize_safety_advantage": False,
        "vf_safety_coef": 0.5,
        "normalize_advantage": True,
        "clip_range": 0.2,
        "learning_rate": 0.0002,
        "ent_coef": 0.005,
        "num_envs": 4,
        "n_steps": 8192,
        "env_id": "SafetyBallRun-v0",
        "loss_type": CombinedLoss(safety_advantage_factor=0., ratio_estimator="PPO"),
        "gamma": 0.99,
        "gamma_s": 0.995,
        "lagrange_beta": 0.5,
        "safety_k": 4,
        "reward_bias": 1.0,
        "batch_size": 64,
        "augmented_state_cumulative_cost_zero": False,
        "policy_kwargs": {},
        "max_grad_norm": 1.5,
    },
    "SafetyCarGather": {},
    "SafetyBallReach-v0": {
        "n_epochs": 5,
        "normalize_safety_advantage": False,
        "vf_safety_coef": 0.5,
        "normalize_advantage": True,
        "clip_range": 0.2,
        "learning_rate": 0.0004,
        "ent_coef": 0.01,
        "num_envs": 4,
        "n_steps": 8192,
        "env_id": "SafetyBallReach-v0",
        "loss_type": CombinedLoss(safety_advantage_factor=0., ratio_estimator="PPO"),
        "gamma": 0.99,
        "gamma_s": 0.995,
        "safety_k": 4,
        "lagrange_beta": 0.0,
        "reward_bias": 0.01,
        "batch_size": 64,
        "augmented_state_cumulative_cost_zero": False,
        "policy_kwargs": {}
    },
    "SafetyBallCircle-v0": {
        "env_id": "SafetyBallCircle-v0",
        "n_epochs": 5,
        "normalize_safety_advantage": True,
        "vf_safety_coef": 0.5,
        "normalize_advantage": True,
        "clip_range": 0.2,
        "learning_rate": 0.0002,
        "ent_coef": 0.01,
        "num_envs": 4,
        "n_steps": 8192,
        "loss_type": CombinedLoss(safety_advantage_factor=0., ratio_estimator="PPO"),
        "gamma": 0.99,
        "gamma_s": 0.995,
        "safety_k": 2,
        "reward_bias": 1.5,
        "batch_size": 64,
        "augmented_state_cumulative_cost_zero": False,
        "use_advantage_r": True,
        "max_grad_norm": 0.8,
    },
    "SafetyBallGather-v0": {
        "n_epochs": 5,
        "normalize_safety_advantage": False,
        "vf_safety_coef": 0.05,
        "normalize_advantage": True,
        "clip_range": 0.2,
        "learning_rate": 0.0002,
        "ent_coef": 0.01,
        "num_envs": 4,
        "n_steps": 8192,
        "env_id": "SafetyBallGather-v0",
        "loss_type": CombinedLoss(safety_advantage_factor=0., ratio_estimator="PPO"),
        "gamma": 0.99,
        "gamma_s": 0.995,
        "safety_k": 4,
        "lagrange_beta": 15.0,
        "reward_bias": 0.00,
        "batch_size": 64,
        "augmented_state_cumulative_cost_zero": False,
        "max_grad_norm": 0.8,
    },
    "SafetyCarCircle-v0": {
        "n_epochs": 5,
        "normalize_safety_advantage": False,
        "vf_safety_coef": 0.5,
        "normalize_advantage": True,
        "clip_range": 0.2,
        "learning_rate": 0.0002,
        "ent_coef": 0.00,
        "num_envs": 4,
        "n_steps": 8192*2,
        "env_id": "SafetyCarCircle-v0",
        "loss_type": CombinedLoss(safety_advantage_factor=0., ratio_estimator="PPO_INV"),
        "gamma": 0.99,
        "gamma_s": 0.995,
        "safety_k": 1,
        "reward_bias": 1.5,
        "batch_size": 64,
        "augmented_state_cumulative_cost_zero": False,
        "use_advantage_r": True,
        "max_grad_norm": 0.8,
    },
}
